FROM amazoncorretto:17.0.7

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS

#RUN adduser --system --shell /bin/sh msinvoicecomodato
#WORKDIR /home/msinvoicecomodato

#ADD entrypoint.sh entrypoint.sh
#RUN chmod 755 entrypoint.sh && chown msinvoicecomodato entrypoint.sh
#USER msinvoicecomodato

#RUN mkdir data
#RUN chmod -R 766 data/

#EXPOSE 8082

#ADD target/*.jar invoicecomodato-0.0.1-SNAPSHOT.jar

#ENTRYPOINT ["./entrypoint.sh"]
COPY ./target/invoicecomodato-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app
EXPOSE 8082
CMD ["java", "-jar", "invoicecomodato-0.0.1-SNAPSHOT.jar"]
