FROM openjdk:17.0.2-slim

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS

RUN adduser --system --shell /bin/sh globalsi
WORKDIR /home/globalsi

COPY comodato-0.0.1-SNAPSHOT.jar app.jar
RUN chown globalsi app.jar

COPY entrypoint.sh entrypoint.sh
RUN chmod 755 entrypoint.sh && chown globalsi entrypoint.sh
USER globalsi

RUN mkdir data
RUN chmod -R 766 data/

EXPOSE 8081
ENTRYPOINT ["./entrypoint.sh"]


#COPY ./generateinvoice-0.0.1-SNAPSHOT.jar /usr/app/
#WORKDIR /usr/app
#EXPOSE 8081
#CMD ["java", "-jar", "generateinvoice-0.0.1-SNAPSHOT.jar"]
